version: "3"
services:

  tsaodai1_1:
    restart: always
    image: "192.168.0.102:8098/tsaodai/tickmine:latest"
    container_name: tickmine_tsaodai1_1
    environment:
      - run_mode=debug
      - database=tsaodai
    volumes:
      - /home/zhoufan/code/quantation:/share/quantation
      - /home/zhoufan/baidunetdisk/tsaodai:/share/database
    ports:
      - "8120:11332"
    tty: true
    stdin_open: true

  citic1_1:
    restart: always
    image: "192.168.0.102:8098/tsaodai/tickmine:latest"
    container_name: tickmine_citic1_1
    environment:
      - run_mode=debug
      - database=citic
    volumes:
      - /home/zhoufan/code/quantation:/share/quantation
      - /home/zhoufan/baidunetdisk/citic:/share/database
    ports:
      - "8110:11332"
    tty: true
    stdin_open: true

  citic2_1:
    restart: always
    image: "192.168.0.102:8098/tsaodai/tickmine:latest"
    container_name: tickmine_citic2_1
    environment:
      - run_mode=debug
      - database=citic
    volumes:
      - /home/zhoufan/code/quantation:/share/quantation
      - /home/zhoufan/baidunetdisk/citic2:/share/database
    ports:
      - "8140:11332"
    tty: true
    stdin_open: true

  zhongtai1_1:
    restart: always
    image: "192.168.0.102:8098/tsaodai/tickmine:latest"
    container_name: tickmine_zhongtai1_1
    environment:
      - run_mode=debug
      - database=zhongtai
    volumes:
      - /home/zhoufan/code/quantation:/share/quantation
      - /home/zhoufan/baidunetdisk/zhongtai:/share/database
    ports:
      - "8130:11332"
    tty: true
    stdin_open: true